=== patrickchartrand/academia/XML/tp2/tp2q2.xsd
<!-- Patrick Chartrand (20017273) -->
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- balise 'bibliothèque' -->
    <xs:element name="bibliothèque">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="membres">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="membre" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="abonné" type="personne_type"/>
                                        <xs:element name="référence" type="personne_type"/>
                                        <xs:element name="emprunts" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="livre-emprunt" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="date_prévue" type="xs:date"/>
                                                                <xs:element name="date_retournée" type="xs:date" minOccurs="0"/>
                                                            </xs:all>
                                                            <xs:attribute name="livre-id" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="retards" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="livre-emprunt" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="date_prévue" type="xs:string"/>
                                                                <xs:element name="date_retournée" type="xs:string"/>
                                                                <xs:element name="montant">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:float">
                                                                            <xs:minExclusive value="0.0"/>
                                                                            <xs:maxExclusive value="100.0"/>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                            </xs:all>
                                                            <xs:attribute name="livre-id" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="livres">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="livre" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titre" type="xs:string"/>
                                        <xs:element name="auteur" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nom" type="xs:string"/>
                                                    <xs:element name="prenom" type="xs:string"/>
                                                    <xs:element name="initiales" type="xs:string" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="isbn" type="xs:string"/>
                                        <xs:element name="cdrom" type="present_type"/>
                                        <xs:element name="photo" type="xs:string" minOccurs="0"/>
                                        <xs:element name="éditeur" type="xs:string"/>
                                        <xs:element name="nb-pages" type="xs:positiveInteger" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="numéro" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- les types globaux -->
    <xs:complexType name="adresse_type">
        <xs:sequence>
            <xs:element name="numéro" type="xs:string"/>
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="ville" type="xs:string"/>
            <xs:element name="code_postal">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][0-9][A-Z]\s*[0-9][A-Z][0-9]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="province">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="AB"/>
                        <xs:enumeration value="BC"/>
                        <xs:enumeration value="MB"/>
                        <xs:enumeration value="NB"/>
                        <xs:enumeration value="NL"/>
                        <xs:enumeration value="NT"/>
                        <xs:enumeration value="NS"/>
                        <xs:enumeration value="NU"/>
                        <xs:enumeration value="ON"/>
                        <xs:enumeration value="PE"/>
                        <xs:enumeration value="QC"/>
                        <xs:enumeration value="SK"/>
                        <xs:enumeration value="YT"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="num_tel_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="personne_type">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prénom" type="xs:string"/>
            <xs:element name="adresse" type="adresse_type"/>
            <xs:element name="téléphone" type="téléphone_type"/>
            <xs:element name="date-naissance" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="present_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="oui"/>
            <xs:enumeration value="non"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="téléphone_type">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="maison" type="num_tel_type"/>
            <xs:element name="cellulaire" type="num_tel_type"/>
            <xs:element name="fax" type="num_tel_type"/>
        </xs:choice>
    </xs:complexType>
    
</xs:schema>

=== patrickchartrand/academia/XML/tp2/tp2q4.xml
<!-- Patrick Chartrand (20017273) -->
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="tp2q4.css"?>
<?xml-stylesheet type="text/css" href="tp2q3.css"?>
<bibliothèque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tp2q2.xsd">
    <membres>
        <membre>
            <abonné>
                <nom>Blo</nom>
                <prénom>Jo</prénom>
                <adresse>
                    <numéro>123</numéro>
                    <rue>Laval</rue>
                    <ville>Montréal</ville>
                    <code_postal>A0A0A0</code_postal>
                    <province>QC</province>
                </adresse>
                <téléphone>
                    <cellulaire>514-999-1234</cellulaire>
                    <maison>514-999-1235</maison>
                </téléphone>
                <date-naissance>1990-05-04</date-naissance>
            </abonné>
            <référence>
                <nom>Blo</nom>
                <prénom>Jo</prénom>
                <adresse>
                    <numéro>125</numéro>
                    <rue>Laval</rue>
                    <ville>Montréal</ville>
                    <code_postal>A0A0A0</code_postal>
                    <province>QC</province>
                </adresse>
                <téléphone>
                    <cellulaire>514-999-1236</cellulaire>
                    <maison>514-999-1237</maison>
                </téléphone>
                <date-naissance>1990-08-04</date-naissance>
            </référence>
            <retards>
                <livre-emprunt livre-id="QA9123-1232-F">
                    <date_prévue>2009-08-02</date_prévue>
                    <date_retournée>2009-08-12</date_retournée>
                    <montant>1.00</montant>
                </livre-emprunt>
                <livre-emprunt livre-id="QA9123-1232-F">
                    <date_prévue>2009-08-22</date_prévue>
                    <date_retournée>2009-08-25</date_retournée>
                    <montant>0.30</montant>
                </livre-emprunt>
            </retards>
        </membre>
        <membre>
            <abonné>
                <nom>Toto</nom>
                <prénom>Titi</prénom>
                <adresse>
                    <numéro>199</numéro>
                    <rue>rue2</rue>
                    <ville>ville2</ville>
                    <code_postal>A0A0A0</code_postal>
                    <province>AB</province>
                </adresse>
                <téléphone>
                    <fax>789-100-9999</fax>
                    <maison>789-100-9998</maison>
                </téléphone>
                <date-naissance>1988-01-04</date-naissance>
            </abonné>
            <référence>
                <nom>Toto</nom>
                <prénom>Tata</prénom>
                <adresse>
                    <numéro>199</numéro>
                    <rue>rue3</rue>
                    <ville>ville3</ville>
                    <code_postal>A0A0A0</code_postal>
                    <province>AB</province>
                </adresse>
                <téléphone>
                    <maison>200-000-0000</maison>
                    <cellulaire>200-000-0000</cellulaire>
                </téléphone>
                <date-naissance>1966-05-04</date-naissance>
            </référence>
            <emprunts>
                <livre-emprunt livre-id="QA9123-1232-F">
                    <date_prévue>2009-09-02</date_prévue>
                </livre-emprunt>
            </emprunts>
        </membre>
    </membres>
    <livres>
        <livre numéro="QA9123-1232-F">
            <titre>Learning XML</titre>
            <auteur>
                <nom>Erik</nom>
                <prenom>Kay</prenom>
            </auteur>
            <auteur>
                <nom>Chose</nom>
                <prenom>Truc</prenom>
            </auteur>
            <isbn>isbn0</isbn>
            <cdrom>oui</cdrom>
            <photo>learningXML2.gif</photo>
            <éditeur>O'Reilly</éditeur>
            <nb-pages>395</nb-pages>
        </livre>
        <livre numéro="QA9123-1999-G">
            <titre>XML in a nutshell</titre>
            <auteur>
                <nom>Rusty</nom>
                <prenom>Harold</prenom>
                <initiales>(R)</initiales>
            </auteur>
            <auteur>
                <nom>Scott</nom>
                <prenom>Means</prenom>
                <initiales>(W)</initiales>
            </auteur>
            <isbn>isbn1</isbn>
            <cdrom>non</cdrom>
            <photo>XMLnutshell.gif</photo>
            <éditeur>O'Reilly</éditeur>
        </livre>
    </livres>
</bibliothèque>
